language: node_js
node_js:
  - 'lts/*'
cache: yarn
stages:
  - Install
  - Build
  - Test
jobs:
  include:
    - stage: Install
      script: yarn install
    - stage: Build
      script: yarn build
    - stage: Test
      script: yarn test